[package]
name = "libbpf-cross-compile"
version = "0.1.0"
edition = "2024"

[dependencies]
libbpf-rs = { version = "0.26.0", features = [
    "static",
], default-features = false }

[build-dependencies]
libbpf-cargo = { version = "0.26.0" }
