[package]
name = "libbpf-cross-compile"
version = "0.1.0"
edition = "2024"

[dependencies]
libbpf-rs = { git = "https://github.com/amirbou/libbpf-rs.git", features = ["static"], default-features = false }

[build-dependencies]
libbpf-cargo = { git = "https://github.com/amirbou/libbpf-rs.git" }
